name: "cd-backend"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull henriquejm98/harbor-backend:latest

      - name: Stop Docker container
        run: docker stop harbor-backend || true

      - name: Remove Docker container
        run: docker rm harbor-backend || true

      - name: Run Docker container
        run: docker run --name harbor-backend -d -p 8080:8080 henriquejm98/harbor-backend:latest
