name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Etapa 2: Configurar Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Você pode escolher 'zulu' ou 'adopt'
          cache: maven

      # Etapa 3: Configurar cache do Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Etapa 4: Construir a aplicação
      - name: Build Application
        run: mvn -B package -DskipTests
        working-directory: ./harbor-api

      # Etapa 5: Executar testes
      - name: Run Tests
        run: mvn test
        working-directory: ./harbor-api
  docker:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./harbor-api
          push: true
          tags: henriquejm98/harbor-backend:latest
