name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v3

      # Etapa 2: Configurar Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Você pode escolher 'zulu' ou 'adopt'
          cache: maven

      # Etapa 3: Configurar cache do Maven
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Etapa 4: Construir e testar a aplicação
      - name: Build and Test
        run: mvn -B package -DskipTests

      # Etapa 5: Relatório de cobertura de código (opcional)
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/ # Diretório de relatórios do Maven

      # Etapa 6: Verificar qualidade do código com cobertura (opcional)
      - name: Generate Coverage Report
        run: mvn jacoco:report
        # Adicione plugins como SonarQube, se necessário, para análise adicional.
