name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List repository files
        run:
          echo "Listing root files:"
          ls -la
          echo "Listing harbor-api directory:"
          ls -la ./harbor-api || echo "harbor-api not found"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Application
        run: mvn -B package -DskipTests
        working-directory: ./harbor-api

      - name: Run Tests
        run: mvn test
        working-directory: ./harbor-api

  docker:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check Dockerfile
        run: |
          if [ ! -f ./harbor-api/Dockerfile ]; then
            echo "Dockerfile not found in ./harbor-api"
            exit 1
          else
            echo "Dockerfile found in ./harbor-api"
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./harbor-api
          push: true
          tags: henriquejm98/harbor-backend:latest
